backend:
  name: github
  repo: christiantownsend/portfolio
  branch: main # Branch to update (optional; defaults to master)

local_backend: false

site_url: https://ctownsend.me
logo_url: "/static/favicon.svg"

media_folder: "docs/.vuepress/public/static"
public_folder: "/static/"
collections:
  - name: "pages"
    label: "Pages"
    editor:
      preview: false
    files:
      - label: "Profile"
        name: "profile"
        file: "docs/profile/index.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "info"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Image", name: "image", widget: "image"}
          - label: "Links"
            name: "links"
            widget: "list"
            fields:
              - {label: "Text", name: "text", widget: "string"}
              - {label: "Link", name: "link", widget: "string"}
          - label: "Interests"
            name: "interests"
            widget: "list"
            field: {label: "Interest", name: "interest", widget: "string"}
  - name: "work" # Used in routes, e.g., /admin/collections/blog
    label: "Work" # Used in the UI
    label_singular: "Project"
    editor:
      preview: false
    folder: "docs/work" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    preview_path: "work/{{slug}}"
    sortable_fields: ['order', 'year', 'title']
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "project"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Year", name: "year", widget: "string"}
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Visible", name: "visible", widget: "boolean"}
      - {label: "Vimeo ID", name: "vimeo", widget: "string"}
      - {label: "Thumbnail", name: "thumb", widget: "image", allow_multiple: false}
      - label: "Categories"
        name: "tags"
        widget: "list"
        default: ["Type"]
      - label: "Collaborators"
        name: "collaborators"
        widget: "list"
        fields:
          - {label: "Name", name: "name", widget: "string"}
          - {label: "Link", name: "link", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown", buttons: [], editor_components: ["image"], modes: ["raw", "rich_text"]}