backend:
  name: github
  repo: christiantownsend/portfolio
  branch: main # Branch to update (optional; defaults to master)
media_folder: "docs/.vuepress/public/static"
public_folder: "docs/.vuepress/dist/"
collections:
  - name: "project" # Used in routes, e.g., /admin/collections/blog
    label: "Project" # Used in the UI
    folder: "docs/work" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}